/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthletesAthleteIdRouteImport } from './routes/athletes/$athleteId'

const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesAthleteIdRoute = AthletesAthleteIdRouteImport.update({
  id: '/athletes/$athleteId',
  path: '/athletes/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/reports': typeof ReportsRoute
  '/roster': typeof RosterRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/reports': typeof ReportsRoute
  '/roster': typeof RosterRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/reports': typeof ReportsRoute
  '/roster': typeof RosterRoute
  '/athletes/$athleteId': typeof AthletesAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/reports' | '/roster' | '/athletes/$athleteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/reports' | '/roster' | '/athletes/$athleteId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/reports'
    | '/roster'
    | '/athletes/$athleteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ReportsRoute: typeof ReportsRoute
  RosterRoute: typeof RosterRoute
  AthletesAthleteIdRoute: typeof AthletesAthleteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes/$athleteId': {
      id: '/athletes/$athleteId'
      path: '/athletes/$athleteId'
      fullPath: '/athletes/$athleteId'
      preLoaderRoute: typeof AthletesAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ReportsRoute: ReportsRoute,
  RosterRoute: RosterRoute,
  AthletesAthleteIdRoute: AthletesAthleteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
